import Head from 'next/head'
import Navbar from '../components/Layout/Navbar/Navbar'
import Sidebar from '../components/Layout/Sidebar/Sidebar'
import Table from '../components/Table/Table'

const Home = () => {
  return (
    <>
      <Head>
        <title>Women Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      {/* <Sidebar/> */}
      <main>
        <Table/>
      </main>
    </>
  )
}

export default Home